name: "Tvheadend (Custom)"
version: "4.3-iCAM"
slug: "tvheadend_custom"
description: "Tvheadend Server 4.3 mit iCAM-Unterstützung"
arch:
  - aarch64
  - amd64
init: false
host_network: true
ingress: true
ingress_port: 9981
devices:
  - "/dev/dvb:/dev/dvb:rwm"
